### ISSUE TITLE
Crash on 1.16.2 fabric

### ISSUE THREAD

**Issue by Neubulae** [18107/Flex-FOV-fabric#2]
[14:26:53] [main/FATAL]: Mixin prepare failed preparing ExampleMixin in modid.mixins.json: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException The specified mixin 'net.fabricmc.example.mixin.ExampleMixin' was not found
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: The specified mixin 'net.fabricmc.example.mixin.ExampleMixin' was not found
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:855) ~[sponge-mixin-0.8.1+build.21.jar:0.8.1+build.21+unknown-b21.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:715) ~[sponge-mixin-0.8.1+build.21.jar:0.8.1+build.21+unknown-b21.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:652) ~[sponge-mixin-0.8.1+build.21.jar:0.8.1+build.21+unknown-b21.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:515) [sponge-mixin-0.8.1+build.21.jar:0.8.1+build.21+unknown-b21.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:440) [sponge-mixin-0.8.1+build.21.jar:0.8.1+build.21+unknown-b21.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:416) [sponge-mixin-0.8.1+build.21.jar:0.8.1+build.21+unknown-b21.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:285) [sponge-mixin-0.8.1+build.21.jar:0.8.1+build.21+unknown-b21.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191) [sponge-mixin-0.8.1+build.21.jar:0.8.1+build.21+unknown-b21.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) [sponge-mixin-0.8.1+build.21.jar:0.8.1+build.21+unknown-b21.git-unknown]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) [fabric-loader-0.9.2+build.206.jar:0.8.1+build.21+unknown-b21.git-unknown]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) [fabric-loader-0.9.2+build.206.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143) [fabric-loader-0.9.2+build.206.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) [?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:427) [?:?]
	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45) [fabric-loader-0.9.2+build.206.jar:?]
	at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:114) [fabric-loader-0.9.2+build.206.jar:?]
	at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:101) [fabric-loader-0.9.2+build.206.jar:?]
	at net.fabricmc.loader.EntrypointStorage.getEntrypointContainers(EntrypointStorage.java:186) [fabric-loader-0.9.2+build.206.jar:?]
	at net.fabricmc.loader.FabricLoader.getEntrypointContainers(FabricLoader.java:251) [fabric-loader-0.9.2+build.206.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:44) [fabric-loader-0.9.2+build.206.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36) [fabric-loader-0.9.2+build.206.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138) [fabric-loader-0.9.2+build.206.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.9.2+build.206.jar:?]
Caused by: java.lang.ClassNotFoundException: The specified mixin 'net.fabricmc.example.mixin.ExampleMixin' was not found
	at org.spongepowered.asm.mixin.transformer.MixinInfo.loadMixinClass(MixinInfo.java:1297) ~[sponge-mixin-0.8.1+build.21.jar:0.8.1+build.21+unknown-b21.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:848) ~[sponge-mixin-0.8.1+build.21.jar:0.8.1+build.21+unknown-b21.git-unknown]
	... 23 more

**Comment by Neubulae** [comment]
I don't see anything related to ExampleMixin in the json file, quite perculiar

**Comment by Neubulae** [comment]
full log as such
[latest.log](https://github.com/18107/Flex-FOV-fabric/files/5128273/latest.log)

**Comment by 18107** [comment]
It looks like you have 159 mods installed. Can you please try just using this mod with fabric-api to confirm that this is the mod causing the crash?

**Comment by Neubulae** [comment]
> It looks like you have 159 mods installed. Can you please try just using this mod with fabric-api to confirm that this is the mod causing the crash?

It worked, weird. I'll try to find which mod is causing the conflict

**Comment by Neubulae** [comment]
It was Vanilla Ingredients Cooking Expanded causing the conflict. Sorry for the problem.
